"""Run the class-centric ontology viewer or the legacy Semantica graph UI."""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path


if __package__ in {None, ""}:
    # Allow direct file execution as well as module execution.
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Serve the FIBO T-BOX in the local Semantica Explorer"
    )
    parser.add_argument(
        "--mode",
        choices=["viewer", "graph"],
        default="viewer",
        help="Use the class-centric ontology viewer or the legacy graph UI",
    )
    parser.add_argument(
        "--graph",
        type=Path,
        default=Path("artifacts/fibo/fibo-prod-tbox-explorer.json"),
        help="Explorer graph JSON generated by export-explorer",
    )
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=5173)
    parser.add_argument("--api-key", default=None, help="Optional API key for the local service")
    parser.add_argument(
        "--ttl",
        type=Path,
        default=Path("artifacts/cnfo/cnfo-fibo-fund-tbox.ttl"),
        help="Merged Turtle ontology used by the class-centric viewer",
    )
    return parser


def run(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.mode == "viewer":
        if __package__ in {None, ""}:
            from fondontology.viewer import OntologyViewerSession, create_viewer_app
        else:
            from .viewer import OntologyViewerSession, create_viewer_app
        import uvicorn

        session = OntologyViewerSession(args.ttl)
        uvicorn.run(create_viewer_app(session), host=args.host, port=args.port, log_level="info")
        return 0

    graph_path = args.graph.expanduser().resolve()
    if not graph_path.is_file():
        raise FileNotFoundError(
            f"Explorer graph not found: {graph_path}. Run export-explorer first."
        )

    if args.api_key:
        os.environ["SEMANTICA_API_KEY"] = args.api_key
        os.environ.pop("SEMANTICA_ALLOW_ANONYMOUS", None)
    elif args.host in {"127.0.0.1", "localhost", "::1"}:
        os.environ.setdefault("SEMANTICA_ALLOW_ANONYMOUS", "true")

    from semantica.explorer.app import create_app
    from semantica.explorer.session import GraphSession
    import uvicorn

    session = GraphSession.from_file(str(graph_path))
    app = create_app(session=session)
    uvicorn.run(app, host=args.host, port=args.port, log_level="info")
    return 0


if __name__ == "__main__":
    raise SystemExit(run())
